---
- name: This play installs needed tools to provision infrastructure VMs
  hosts: vm_host
  vars_files:
    - vars/libvirt.yml
  tasks:

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install required packages
      yum:
        name: "{{ virtualization_packages.centos8 }}"
        state: latest
      become: true
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version | int == 8

    - name: Install required packages
      yum:
        name: "{{ virtualization_packages.centos7 }}"
        state: latest
      become: true
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version | int == 7

    - name: Install required packages
      yum:
        name: "{{ virtualization_packages.fedora }}"
        state: latest
      become: true
      when:
        - ansible_distribution == 'Fedora'

    - name: Download and provision Terraform
      unarchive: 
        src: "{{ terraform_url }}"
        dest: /usr/bin/
        mode: 755
        remote_src: yes
      become: true

    - name: Virtualization services are enabled
      service:
        name: libvirtd
        state: started
        enabled: true
      become: true

    - name: Clone libvirt-provider for terraform 
      git:
        repo: "{{ libvirt_provider_repo }}"
        dest: ~/libvirt-provider
        force: true

    - name: Run 'install' target on libivrt-provider
      make:
        chdir: ~/libvirt-provider
        target: install

    - name: Ensures terraform plugins directory exists
      file:
        #path: ~/.terraform.d/plugins
        path: "{{ libvirt_plugin_dir }}"
        state: directory
        mode: 0744

    - name: Copy libvirt provider to plugins directory
      copy:
        src: "{{ gopath }}/bin/terraform-provider-libvirt"
        dest: "{{ libvirt_plugin_dir }}"
        remote_src: true
        mode: 0755
