---
- name: This play installs needed tools to provision infrastructure VMs
  hosts: vm_host
  become: true
  tasks:
    - name: Manage packets when distro is 'CentOS'
      block:
      - name: Upgrade all packages
        yum:
          name: '*'
          state: latest

      - name: Install required packages
        yum:
          name: "{{ os_packages.centos }}"
          state: latest
        when:
          - ansible_distribution == 'CentOS'

      - name: Install required packages
        yum:
          name: "{{ os_packages.fedora }}"
          state: latest
        when:
          - ansible_distribution == 'Fedora'

      when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS'

    - name: Manage packets when distro is 'Ubuntu'
      block:
      - name: Upgrade all packages
        apt:
          name: '*'
          state: latest

      - name: Install required packages
        apt:
          name: "{{ os_packages.ubuntu }}"
          state: latest

      when: ansible_distribution == 'Ubuntu'

    - name: Download and provision Terraform
      unarchive: 
        src: "{{ terraform_url }}"
        dest: /usr/bin/
        mode: 0755
        remote_src: yes

    - name: Virtualization services are enabled
      service:
        name: libvirtd
        state: started
        enabled: true
