- name: This play ensures environment is set up for cluster creation
  hosts: vm_host
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - name: Ensure cluster folder exists
      file:
        path: "clusters/{{ k8s.cluster_name }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}" 
        mode: 0755

    - name: Populate cluster folder with terraform files
      copy:
        src: "files/terraform/"
        dest: "clusters/{{ k8s.cluster_name }}"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: 0755

    - name: Snapshot cluster configuration for further use
      copy:
        src: "vars/k8s_cluster.yml"
        dest: "clusters/{{ k8s.cluster_name }}/"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: 0755

    - name: Ensure helm is installed
      unarchive:
        src: "{{ helm.helm_installer }}"
        dest: /tmp/
        remote_src: true

    - name: Install helm in PATH
      copy:
        src: /tmp/linux-amd64/helm
        dest: /usr/local/bin/
        remote_src: true
        mode: +x
      become: true

    - name: Install Helm Diff
      kubernetes.core.helm_plugin:
        state: present
        plugin_path: https://github.com/databus23/helm-diff

    - name: remove directory
      file:
        path: /tmp/linux-amd64
        state: absent

    - name: Ensure needed pip packages are present
      pip:
        executable: pip3
        name: "{{ item }}"
      loop: 
        - PyYAML
        - kubernetes
        - jsonpatch
