---
- name: Provision storage on nodes
  hosts: k8s_nodes
  become: true
  vars: 
    paths:
      - dev: /dev/vdb1
        path: /var/lib/kubelet
  tasks:
    - name: Create kubelet partition
      parted:
        device: /dev/vdb
        label: msdos
        number: 1
        part_start: 0%
        part_end: 100%
        #part_end: 5%
        state: present

    - name: Create filesystem on partitions
      filesystem:
        fstype: ext4
        dev: "{{ item.dev }}"
      loop: "{{ paths }}"

    - name: Create mountpoints
      file: 
        path: "{{ item.path }}"
        state: directory
      loop: "{{ paths }}"

    - name: Mount the filesystems
      mount:
        fstype: ext4
        src: "{{ item.dev }}"
        path: "{{ item.path }}"
        state: mounted
      loop: "{{ paths }}"
