- name: This play provisions k8s VMs based on intial config
  hosts: vm_host
  tasks:
    - name: Delete image file
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/{{ image_name }}.qcow2
        - /tmp/{{ image_name }}-master.qcow2
        - /tmp/{{ image_name }}-worker.qcow2
