- name: This play provisions k8s VMs based on intial config
  hosts: vm_host
  tasks:
    - name: Delete image file
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/CentOS-7-x86_64-GenericCloud.qcow2
        - /tmp/CentOS-7-x86_64-GenericCloud-master.qcow2
        - /tmp/CentOS-7-x86_64-GenericCloud-worker.qcow2
