---
- name: Loadbalancer configuration play
  hosts: loadbalancer
  become: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - block:
        - name: Install python on CentOS8
          raw: dnf -y install python36
          when: k8s.cluster_os == 'CentOS8'

        - name: Upgrade all packages
          yum:
            name: '*'
            state: latest

        - name: Install packages
          yum:
            name: "{{ packages }}"
            state: latest
              
        - name: Enable firewalld
          service:
            name: "{{ item }}"
            enabled: true
            state: started
          loop:
            - firewalld
            - haproxy
            - NetworkManager

        # Workaround to fix firewalld zone not persisting after reboot: https://github.com/firewalld/firewalld/issues/195
 
        - name: Set interface to internal zone 
          shell: nmcli connection modify System\ eth0 connection.zone internal
          when: k8s.cluster_os == 'CentOS7'

        - name: Set interface to internal zone
          shell: nmcli connection modify eth0 connection.zone internal
          when: k8s.cluster_os == 'CentOS8'

        - name: Stop NetworkManager
          service: 
            name: NetworkManager
            state: stopped

        - name: Adding interface to firewall internal zone  
          firewalld:
            zone: internal
            interface: "eth0"
            permanent: yes
            state: enabled

        - name: Start NetworkManager
          service:
            name: NetworkManager
            state: started
            enabled: true

        - name: Allow service for internal zone
          firewalld:
            zone: internal
            state: enabled
            permanent: yes
            service: "{{ item }}"
          loop: "{{ services }}"

        - name: Allow ports for internal zone
          firewalld:
            zone: internal
            state: enabled
            permanent: yes
            port: "{{ item }}"
          loop: "{{ internal_zone_port }}"

        - name: Reload firewalld service
          service:
            name: firewalld
            state: restarted 

        - name: Enabling selinux boolean for haproxy
          seboolean:
            name: haproxy_connect_any
            state: yes
            persistent: yes

        - name: Firing haproxy template
          template:
            src: templates/haproxy.j2
            dest: /etc/haproxy/haproxy.cfg

        - name: Reload haproxy service
          service:
            name: haproxy
            state: restarted
            enabled: true
        
        - name: Reboot loadbalancer
          reboot: 
      when: k8s.control_plane.vms > 1

