---
- name: Ensure kube packages are installed
  hosts: k8s_nodes
  become: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - name: Add Kubernetes repository
      yum_repository:
        name: kubernetes
        description: Kubernetes repo
        baseurl: "{{ kubernetes.k8s_repo }}"
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: "{{ kubernetes.k8s_repo_key }}"
        exclude: kubelet kubeadm kubectl

    - name: Disable swap
      shell: swapoff -a  

    - name: Remove swap entry from fstab
      lineinfile:
        line: "/dev/mapper/cl-swap swap"  
        path: /etc/fstab
        state: absent
    - name: Disable SELinux
      selinux:
        state: disabled
      register: selinux_output
      notify: reboot

    - name: Install kubepackages
      yum:
        name: "{{ kubernetes.k8s_packages }}"
        disable_excludes: kubernetes

    - name: Install lvm2 for rook_ceph.support and git for installing rook
      yum:
        name: lvm2
      when: rook_ceph.install_rook

    - name: Enable kubelet
      systemd: 
        name: kubelet
        state: started
        enabled: true

  handlers:
    - name: reboot
      reboot:
