---
- name: Ensure kube packages are installed
  hosts: k8s_nodes
  become: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - name: Add Kubernetes repository
      yum_repository:
        name: kubernetes
        description: Kubernetes repo
        baseurl: "{{ kubernetes.centos.k8s_repo }}"
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: "{{ kubernetes.centos.k8s_repo_key }}"
        exclude: kubelet kubeadm kubectl
      when: k8s.cluster_os == 'CentOS'

    - name: Ensure required packages for kubetools are installed
      apt:
        name: 
          - apt-transport-https
          - curl
        state: latest
      when: k8s.cluster_os == 'Ubuntu'

    - name: Add kube-repo key
      apt_key:
        url: "{{ kubernetes.ubuntu.k8s_repo_key }}"
        state: present
      when: k8s.cluster_os == 'Ubuntu'

    - name: Ensure the presence of apt-repo for kubernetes packages
      apt_repository:
        repo: "{{ kubernetes.ubuntu.k8s_repo }}"
        filename: "{{ kubernetes.ubuntu.k8s_repo_file }}"
        state: present
#        update_cache_retries: 25
      when: k8s.cluster_os == 'Ubuntu'
    
    - name: Ensure cri-o is installed
      apt:
        name: "{{ kubernetes.ubuntu.k8s_packages }}"
        state: present
      when: k8s.cluster_os == 'Ubuntu'

    - name: Hold kubepackages
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubectl
        - kubeadm
        - kubelet
      when: k8s.cluster_os == 'Ubuntu'

    - name: Disable swap
      shell: swapoff -a  

    - name: Remove swap entry from fstab
      lineinfile:
        line: "/dev/mapper/cl-swap swap"  
        path: /etc/fstab
        state: absent

    - name: Disable SELinux
      selinux:
        state: disabled
      register: selinux_output
      notify: reboot
      when: k8s.cluster_os == 'CentOS'

    - name: Install kubepackages
      yum:
        name: "{{ kubernetes.centos.k8s_packages }}"
        state: present
        disable_excludes: kubernetes
      when: k8s.cluster_os == 'CentOS'

    - name: Install lvm2 for rook support and git for installing rook
      yum:
        name: 
          - lvm2
          - git
      when: 
        - rook_ceph.install_rook 
        - k8s.cluster_os == 'CentOS'

    - name: Install lvm2 for rook support and git for installing rook
      apt:
        name: 
          - lvm2
          - git
      when: 
        - rook_ceph.install_rook
        - k8s.cluster_os == 'Ubuntu'

    - name: Enable kubelet
      systemd: 
        name: kubelet
        state: started
        enabled: true
      notify: reboot

  handlers:
    - name: reboot
      reboot:
