---
- name: Install cluster with kubeadm
  vars_files:
    - vars/k8s_cluster.yml
  hosts: masters
  tasks:
    - block: 
        - name: Start kubeadm install
          command: kubeadm init --pod-network-cidr 10.100.0.0/17
          become: true
          register: kubeadm_output

        - name: Print output
          debug:
            var: kubeadm_output

      when: k8s.control_plane.vms == 1

    - block:
        - name: Start kubeadm install - HA
          command: sudo kubeadm init --control-plane-endpoint k8s-loadbalancer.k8s.lab --upload-certs
          become: true
          register: ha_kubeadm_output
        - debug:
            var: kubeadm_output
        
        - name: "set certificate key fact"
          set_fact:
            kubecertkey: "{{ kubeadm_output.stdout | regex_search('certificate-key [0-9a-zA-Z]{64}') | regex_search('[0-9a-zA-Z]{64}') }}"
        
      when: 
        - k8s.control_plane.vms > 1
        - inventory_hostname == groups['masters'][0]

    - block
        - name: "set token fact"
          set_fact:
            kubetoken: kubeadm_output | regex_search('--token ([0-9a-zA-Z]{6}.[0-9a-zA-Z]{16})') | regex_search('([0-9a-zA-Z]{6}.[0-9a-zA-Z]{16})')

        - name: "set hash fact"
          set_fact:
            kubehash: kubeadm_output | regex_search('sha256:[0-9a-zA-Z]{64}') | regex_search('[0-9a-zA-Z]{64}')
      when:
        - inventory_hostname == groups['masters'][0]
