---
- name: Apply network plugin
  hosts: masters
  run_once: true
  tasks:
    - name: Apply network addon - Calico
      command: kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml

    - name: Wait for kube-dns pods become created
      shell: "kubectl get po --namespace=kube-system --selector k8s-app=kube-dns --output=jsonpath='{.items[*].metadata.name}'"
      register: kube_dns_pods_created
      until: item in kube_dns_pods_created.stdout
      retries: 10
      delay: 30
      with_items:
        - coredns

    - name: Wait for core-dns pods become ready
      shell: "kubectl wait --namespace=kube-system --for=condition=Ready pods --selector k8s-app=kube-dns --timeout=600s"
      register: kube_dns_pods_ready
