---
- name: Play to join control plane nodes in the cluster
  hosts: masters
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - name: Joining control plane nodes
      block: 
      - name: Fire joinConfiguration template for control plane nodes
        template:
          src: templates/kubeadm-join-config.yaml.j2
          dest: /tmp/kubeadm-join.yaml
      - name: Join control-plane nodes in cluster
        command: kubeadm join --config /tmp/kubeadm-join.yaml
        become: true
      when: 
        - inventory_hostname != groups['masters'][0]
        - k8s.control_plane.vms > 1
