---
- name: Apply network plugin
  hosts: vm_host
  run_once: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - block:
        - name: Download Calico manifest.
          ansible.builtin.get_url:
            url: "{{ item.url }}"
            dest: "{{ item.name }}"
            mode: '0664'
          loop:
            - name: /tmp/calico-operator.yaml
              url: "{{ cni_plugins.calico.calico_operator }}"
            - name: /tmp/calico-crd.yaml
              url: "{{ cni_plugins.calico.calico_crd }}"

        - name: Apply custom CIDR to calico installation manifest
          replace: 
            path: /tmp/calico-crd.yaml
            regexp: 192.168.0.0\/16
            replace: "{{ k8s.network.pod_cidr }}"

        - name: Apply calico manifests to the cluster.
          kubernetes.core.k8s:
            state: present
            src: "{{ item }}"
            kubeconfig: "clusters/{{ k8s.cluster_name }}/admin.kubeconfig"
            wait: yes
          loop: 
            - /tmp/calico-operator.yaml
            - /tmp/calico-crd.yaml
      when: k8s.network.cni_plugin == 'calico'

    - block:
        - name: Add helm chart repository for Cilium
          kubernetes.core.helm_repository:
            name: "{{ item.name }}"
            repo_url: "{{ item.repo_url }}"
          loop:
            - name: "{{ cni_plugins.cilium.chart.name }}" 
              repo_url: "{{ cni_plugins.cilium.chart.url }}"

        - name: Ensure Cilium helm chart is installed
          kubernetes.core.helm:
            name: cilium
            chart_ref: "{{ cni_plugins.cilium.chart.ref }}"
            chart_version: "{{ cni_plugins.cilium.chart.version }}"
            kubeconfig: "clusters/{{ k8s.cluster_name }}/admin.kubeconfig"
            release_namespace: kube-system
            values:
              ipam:
                mode: kubernetes
            wait: true
      when: k8s.network.cni_plugin == 'cilium'

    - block:
        - name: Download flannel manifest
          get_url:
            url: "{{ cni_plugins.flannel.flannel_repo }}"
            dest: /tmp/kube-flannel.yml
        
        - name: Patch kube-flannel to use host-gw instead of vxlan
          replace:
            path: /tmp/kube-flannel.yml
            regexp: 'vxlan'
            replace: 'host-gw'

        - name: Apply flannel manifests to the cluster.
          kubernetes.core.k8s:
            state: present
            src: /tmp/kube-flannel.yml
            kubeconfig: "clusters/{{ k8s.cluster_name }}/admin.kubeconfig"
            wait: yes
      when: k8s.network.cni_plugin == 'flannel'

    - name: Wait for core-dns pods to be up and running
      kubernetes.core.k8s:
        state: present
        api_version: v1
        kind: Deployment
        namespace: kube-system
        name: coredns
        kubeconfig: "clusters/{{ k8s.cluster_name }}/admin.kubeconfig"
        wait: yes
