---
- name: Prepare files for cluster management
  hosts: masters
  tasks:
    - name: Complete setup installing kube-config on all master nodes
      block:
        - name: Create kube directory
          file:
            path: /home/kube/.kube
            state: directory

        - name: Copy kubeconfig
          copy:
            src: /etc/kubernetes/admin.conf
            dest: /home/kube/.kube/config
            remote_src: true
            owner: kube
            group: kube
          become: true
      when: inventory_hostname != groups['masters'][0]

    - name: Fetch kubeconfig file
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: admin.kubeconfig
        flat: yes
      become: true
      when: inventory_hostname == groups['masters'][0]

- name: Label worker nodes, remove taints from master nodes if selected
  hosts: master
  run_once: true
  tasks:
    - name: Label worker nodes
      shell: kubectl label nodes {{ hostvars[item].node_fqdn }} node-role.kubernetes.io/worker=
      loop: groups['workers']

    - name: Remove taint from master nodes
      shell: kubectl taint node {{ hostvars[item].node_fqdn }}  node-role.kubernetes.io/master-
      loop: groups['masters']
      when: k8s.master_schedulable

