---
- name: Prepare deletion playbook for cluster
  hosts: vm_host
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - name: Prepare playbook for cluster deletion
      template:
        src: templates/clenup-playbook.yml.j2
        dest: "{{ k8s.cluster_name }}-cleanup-playbook.yml"

    - name: Delete image file
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/{{ image_name }}.qcow2
        - /tmp/{{ image_name }}-master.qcow2
        - /tmp/{{ image_name }}-worker.qcow2

- name: Label worker nodes, remove taints from master nodes if selected
  hosts: masters
  run_once: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - block: 
      - name: Label worker nodes
        shell: kubectl label nodes {{ hostvars[item].node_fqdn }} node-role.kubernetes.io/worker=
        loop: "{{ groups['workers'] }}"

      - name: Remove taint from master nodes
        shell: kubectl taint node {{ hostvars[item].node_fqdn }}  node-role.kubernetes.io/master-
        loop: "{{ groups['masters'] }}"
        when: k8s.master_schedulable
      when: inventory_hostname == groups['masters'][0]
