--- 
- name: Prepare cluster to install nginx
  hosts: masters
  vars_files:
    - vars/k8s_cluster.yml
  run_once: true
  tasks:
    - block:
        - name: Install CRDs
          shell: kubectl apply -f {{ ingresses.nginx_repo }}
       
        - name: Wait for all ingress-nginx pods become created
          shell: "kubectl get po --namespace=ingress-nginx --output=jsonpath='{.items[*].metadata.name}'"
          register: ingress_nginx_pods_created
          until: item in ingress_nginx_pods_created.stdout
          retries: 10
          delay: 30
          with_items:
            - ingress-nginx-admission-create
            - ingress-nginx-admission-patch
            - ingress-nginx-controller

        - name: Wait for ingress-nginx pods to become ready
          shell: "kubectl wait --namespace=ingress-nginx --for=condition=Ready pods --selector app.kubernetes.io/component=controller  --timeout=600s"
          register: ingress_nginx_pods_ready

        - name: Save nodePorts in master facts
          shell: kubectl get svc ingress-nginx-controller  -n ingress-nginx -o jsonpath='{..spec.ports[?(@.name=="{{ item }}")].nodePort}'
          loop:
            - http
            - https
          register: ports
        
        - name: Save facts
          set_fact:
            ingress_http_port: "{{ ports.results[0].stdout }}" 
            ingress_https_port: "{{ ports.results[1].stdout }}" 
      
      when: ingress_controller.install_ingress_controller and ingress_controller.type == 'nginx'
 
- name: Refresh facts
  hosts: all
  gather_facts: true

- name: Trigger new haproxy configuration
  hosts: loadbalancer
  become: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks: 
    - block:
        - name: Fire up new haproxy template
          template:
            src: templates/haproxy.j2
            dest: /etc/haproxy/haproxy.cfg

        - name: Restart haproxy
          systemd:
            name: haproxy
            state: restarted

      when: ingress_controller.install_ingress_controller and ingress_controller.type == 'nginx' 
