--- 
- name: Prepare cluster to install contour ingress controller
  hosts: masters
  vars_files:
    - vars/k8s_cluster.yml
  run_once: true
  tasks:
    - name: Take all required steps to install contour as ingress controller
      block:
        - name: Install CR
          shell: kubectl apply -f {{ ingresses.contour_repo }} 
       
        - name: Wait for all ingress-contour pods become created
          shell: "kubectl get po --namespace=projectcontour --output=jsonpath='{.items[*].metadata.name}'"
          register: ingress_contour_pods_created
          until: item in ingress_contour_pods_created.stdout
          retries: 10
          delay: 30
          with_items:
            - contour
            - envoy

        - name: Wait for contour and envoy pods pods to become ready
          shell: "kubectl wait --namespace=projectcontour --for=condition=Ready pods --selector=app=contour --timeout=600s"
          register: ingress_contour_pods_ready

        - name: Save nodePorts in master facts
          shell: kubectl get svc envoy -n projectcontour -o jsonpath='{..spec.ports[?(@.name=="{{ item }}")].nodePort}'
          loop:
            - http
            - https
          register: ports
        
        - name: Save facts
          set_fact:
            ingress_http_port: "{{ ports.results[0].stdout }}" 
            ingress_https_port: "{{ ports.results[1].stdout }}" 
      
      when: ingress_controller.install_ingress_controller and ingress_controller.type == 'contour'
    
- name: Refresh facts
  hosts: all
  gather_facts: true

- name: Trigger new haproxy configuration
  hosts: loadbalancer
  become: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks: 
    - block:
        - name: Fire up new haproxy template
          template:
            src: templates/haproxy.j2
            dest: /etc/haproxy/haproxy.cfg

        - name: Restart haproxy
          systemd:
            name: haproxy
            state: restarted
      when: ingress_controller.install_ingress_controller and ingress_controller.type == 'contour'
