--- 
- name: Prepare cluster to install haproxy ingress
  hosts: masters
  vars_files:
    - vars/k8s_cluster.yml
  run_once: true
  tasks:
    - block:
        - name: Install CRDs
          shell: kubectl apply -f {{ ingresses.haproxy_repo }} 
       
        - name: Wait for all ingress-haproxy pods become created
          shell: "kubectl get po --namespace=haproxy-controller --output=jsonpath='{.items[*].metadata.name}'"
          register: ingress_haproxy_pods_created
          until: item in ingress_haproxy_pods_created.stdout
          retries: 10
          delay: 30
          with_items:
            - haproxy-ingress
            - ingress-default-backend

        - name: Wait for ingress-haproxy pods to become ready
          shell: "kubectl wait --namespace=haproxy-controller --for=condition=Ready pods --all --timeout=600s"
          register: ingress_haproxy_pods_ready

        - name: Save nodePorts in master facts
          shell: kubectl get svc haproxy-ingress -n haproxy-controller -o jsonpath='{..spec.ports[?(@.name=="{{ item }}")].nodePort}'
          loop:
            - http
            - https
          register: ports
        
        - name: Save facts
          set_fact:
            ingress_http_port: "{{ ports.results[0].stdout }}" 
            ingress_https_port: "{{ ports.results[1].stdout }}" 
      
      when: ingress_controller.install_ingress_controller and ingress_controller.type == 'haproxy'
    
- name: Refresh facts
  hosts: all
  gather_facts: true

- name: Trigger new haproxy configuration
  hosts: loadbalancer
  become: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks: 
    - block:
        - name: Fire up new haproxy template
          template:
            src: templates/haproxy.j2
            dest: /etc/haproxy/haproxy.cfg

        - name: Restart haproxy
          systemd:
            name: haproxy
            state: restarted
      when: ingress_controller.install_ingress_controller and ingress_controller.type == 'haproxy' 
