--- 
- name: Prepare cluster to install rook
  hosts: masters
  run_once: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - block:
      - name: Install git
        yum:
          name: git
          state: latest
        become: true

      - name: Clone rook repository
        git:
          repo: "{{ rook.rook_repo }}"
          dest: /tmp/rook
          version: "{{ rook.rook_version }}"
          force: true

      - name: Create common resources for rook-ceph
        shell:  "kubectl create -f /tmp/rook/cluster/examples/kubernetes/ceph/common.yaml"
        ignore_errors: true

      - name: Create rook-ceph-operator resource
        shell:  "kubectl create -f /tmp/rook/cluster/examples/kubernetes/ceph/operator.yaml"
        ignore_errors: true

      - name: Wait for operator pod to be ready
        shell: "kubectl wait --namespace=rook-ceph --for=condition=Ready pods -l 'app in (rook-ceph-operator,rook-discover)'  --timeout=600s"

      - name: Create cluster resources for rook_ceph
        shell: "kubectl create -f /tmp/rook/cluster/examples/kubernetes/ceph/cluster.yaml"
        ignore_errors: true

      - name: Wait for all rook-ceph pods become created
        shell: "kubectl get po --namespace=rook-ceph --output=jsonpath='{.items[*].metadata.name}'"
        register: rook_ceph_pods_created
        until: item in rook_ceph_pods_created.stdout
        retries: 20
        delay: 30
        with_items:
          - csi-cephfsplugin
          - csi-cephfsplugin-provisioner
          - csi-rbdplugin
          - csi-rbdplugin-provisioner
          - rook-ceph-crashcollector
          - rook-ceph-mgr
          - rook-ceph-mon
          - rook-ceph-osd

      - name: Wait for cluster pods to be ready (May take a while..)
        shell: "kubectl wait --namespace=rook-ceph --for=condition=Ready pods -l 'app in (csi-cephfsplugin,csi-cephfsplugin-provisioner,csi-rbdplugin,csi-rbdplugin-provisioner,rook-ceph-crashcollector,rook-ceph-mgr,rook-ceph-mon,rook-ceph-osd)' --timeout=600s"
        register: rook_cluster_pod_ready
      when: rook_ceph.install_rook

