--- 
- name: Prepare cluster to install metalLB
  hosts: vm_host
  run_once: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - block:

      - name: Render template for L2 configuration
        template:
          src: templates/metallb-l2.j2
          dest: /tmp/metallb-l2.yaml

      - name: Download metal-lb CR for later apply
        ansible.builtin.get_url:
          url: "{{ item.url }}"
          dest: "{{ item.name }}"
          mode: '0664'
        loop:
          - name: /tmp/metallb-ns.yaml
            url: "{{ metallb_setup.manifest_url }}/namespace.yaml"
          - name: /tmp/metallb.yaml
            url: "{{ metallb_setup.manifest_url }}/metallb.yaml"

      - name: Ensure metal-lb namespace is present
        kubernetes.core.k8s:
          state: present
          src: "{{ item }}"
          kubeconfig: "clusters/{{ k8s.cluster_name }}/admin.kubeconfig"
          wait: yes
        loop:
          - /tmp/metallb-ns.yaml

      - name: Ensure metal-lb is installed in your cluster
        kubernetes.core.k8s:
          state: present
          src: "{{ item }}"
          kubeconfig: "clusters/{{ k8s.cluster_name }}/admin.kubeconfig"
          #wait: yes
          apply: yes
        loop:
          - /tmp/metallb.yaml
          - /tmp/metallb-l2.yaml

      - name: Render template for L2 configuration
        template:
          src: templates/metallb-l2.j2
          dest: /tmp/metallb-l2.yaml

      - name: Ensure metal-lb configmap is added in your cluster
        kubernetes.core.k8s:
          state: present
          src: "/tmp/metallb-l2.yaml"
          kubeconfig: "clusters/{{ k8s.cluster_name }}/admin.kubeconfig"
          wait: yes
          apply: yes
