---
- name: Play for k8s removal
  hosts: masters
  become: true
  tasks:
    - name: Drain node
      shell: kubectl drain {{ inventory_hostname }} --delete-local-data --force --ignore-daemonsets

    - name: Delete node 
      shell: kubectl delete node {{ inventory_hostname }}

- name: Cleanup hosts
  hosts: masters,workers
  become: true
  tasks:

    - name: Reset kubeadm configuration
      shell: kubeadm reset

    - name: Clear iptables rules
      shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
