---
- name: Cleanup playbook
  hosts: vm_host
  vars_files:
    - vars/k8s_cluster.yml
  tasks:

    - name: Destroy cluster VM
      terraform:
        force_init: true
        project_path: "files/terraform/{{ item }}"
        state: absent
      loop:
        - workers
        - workers-rook
        - masters
        - loadbalancer
      when: not rook_ceph.install_rook

    - name: Destroy cluster VM
      terraform:
        force_init: true
        project_path: "files/terraform/{{ item }}"
        state: absent
      loop:
        - workers-rook
        - workers
        - masters
        - loadbalancer
      when: rook_ceph.install_rook

    - name: Remove libvirt network
      virt_net:
        name: "{{ k8s.cluster_name }}"
        state: absent

    - name: Remove libvirt pool
      virt_pool:
        name: "{{ k8s.cluster_name }}"
        state: absent

    - name: Delete all created paths
      file:
        path: "{{ item }}"
        state: absent
      loop: 
        - ~/libvirt-provider
        - ~/.terraform.d
        - ~/go
        - "{{ libvirt.storage.pool_path }}/{{ k8s.cluster_name }}"

    - name: Delete all created paths - root 
      become: true
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/bin/terraform

    - name: Cleanup local DNS config
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/NetworkManager/dnsmasq.d/libvirt_dnsmasq.conf
        - /etc/NetworkManager/conf.d/localdns.conf

    - name: Restart NetworkManager
      service:
        name: NetworkManager
        state: restarted
