---
- name: Cleanup playbook
  hosts: vm_host
  vars_files:
    - vars/k8s_cluster.yml
  become: true
  tasks:

    - name: Destroy cluster VM
      terraform:
        force_init: true
        project_path: "files/terraform/{{ item }}"
        state: absent
      loop:
        - workers
        - masters
        - loadbalancer
      when: not rook_ceph.install_rook

    - name: Destroy cluster VM
      terraform:
        force_init: true
        project_path: "files/terraform/{{ item }}"
        state: absent
      loop:
        - workers-rook
        - workers
        - masters
        - loadbalancer
      when: rook_ceph.install_rook

    - name: Destroy libvirt pool and network 
      terraform:
        force_init: true
        project_path: "files/terraform/libvirt-resources"
        state: absent

    - name: Delete all created paths
      file:
        path: "{{ item }}"
        state: absent
      loop: 
        - ~/libvirt-provider
        - ~/.terraform.d
        - ~/go/bin/terraform-provider-libvirt

    - name: Ensure images are deleted
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/OS-GenericCloud-worker.qcow2
        - /tmp/OS-GenericCloud-master.qcow2
        - /tmp/OS-GenericCloud.qcow2

    - name: Delete all created paths - root 
      become: true
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/bin/terraform

    - name: Cleanup local DNS config
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/NetworkManager/dnsmasq.d/libvirt_dnsmasq.conf
        - /etc/NetworkManager/conf.d/localdns.conf

    - name: Restart NetworkManager and libvirtd
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - libvirtd
        - NetworkManager
