terraform_url: https://releases.hashicorp.com/terraform/1.0.1/terraform_1.0.1_linux_amd64.zip
golang_url: https://golang.org/dl/go1.16.5.linux-amd64.tar.gz

libvirt_provider_repo: https://github.com/dmacvicar/terraform-provider-libvirt.git
libvirt_plugin_dir: ~/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/0.6.3/linux_amd64
image_name: OS-GenericCloud
centos:
  cloud_image: https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20210603.0.x86_64.qcow2
ubuntu:
  cloud_image: https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img
helm:
  helm_installer: https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz
rancher_helm:
  rancher_chart: https://releases.rancher.com/server-charts/latest
  cert_manager_chart: https://charts.jetstack.io
