virtualization_packages:
  centos:
    - unzip
    - git
    - golang
    - gcc
    - make
    - python3-lxml
    - python3-netaddr
    - python3-libvirt
    - libvirt-devel
    - libvirt
    - qemu-kvm
    - virt-install
    - virt-manager

  ubuntu:
    - unzip
    - git
    - golang
    - gcc
    - make
    - python3-lxml
    - python3-netaddr
    - python3-libvirt
    - libvirt-daemon-system
    - libvirt-clients
    - bridge-utils
    - qemu-kvm
    - virtinst
    - virt-manager

  fedora:
    - unzip
    - git
    - golang
    - gcc
    - make
    - python3-lxml
    - python3-netaddr
    - python3-libvirt
    - libvirt-devel
    - libvirt
    - qemu-kvm
    - virt-install
    - virt-manager
