services:
  - nfs
  - mountd
  - rpc-bind
ports:
  - 4001/udp
  - 4001/tcp
  - 2049/tcp
  - 2049/udp

packages_server:
  ubuntu:
    - nfs-kernel-server
  centos:
    - nfs-utils
packages_client:
  ubuntu:
    - nfs-common
    - nfs4-acl-tools
  centos:
    - nfs-utils
    - nfs4-acl-tools

